name: azkark
description: An azkar app for muslim.
publish_to: none

version: 1.1.1+11

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

#  New quran
  another_xlider: ^3.0.2
  audio_service: ^0.18.18
  toastification: ^3.0.3
  connectivity_plus: ^6.1.4
  drift: ^2.27.0

  flutter_cache_manager: ^3.4.1
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  get_storage: ^2.1.1
  lottie: ^3.3.1
  path: ^1.9.0
  rxdart: ^0.28.0
  flutter_sliding_panel: ^0.0.5
  drift_flutter: ^0.2.4

  #------------------------------------------------

  #  pray time
  animated_analog_clock: ^0.2.1
  prayer_time: ^2.0.0
  #------------------------------------------------

  # Localization
  easy_localization: ^3.0.8 # Multi-language support

  # Image and Media
  cached_network_image: ^3.4.1 # Caches images for performance
  flutter_svg: ^2.1.0 # Renders SVG images



  # Notifications and Permissions
  flutter_local_notifications: ^19.4.0 # Local push notifications
  permission_handler: ^12.0.1 # Manage device permissions




  # State management
  provider: ^6.1.5 # Manages app state efficiently
  flutter_bloc: ^9.1.1

  equatable: ^2.0.7 # Equality comparison

  # Network
  dio: ^5.9.0 # Powerful HTTP client for API requests



  # Local Storage
  shared_preferences: ^2.5.3 # Persistent storage



  # File Handling
  photo_view: ^0.15.0 # Zoomable image viewer

  # Maps
  geolocator: ^13.0.2 # Provides geolocation services
  geolocator_android: 4.6.1


  share_plus: ^11.1.0 # Share content across apps

  # UI Components
  shimmer: ^3.0.0 # Shimmer loading effect

  flutter_html: ^3.0.0-beta.2 # HTML rendering

  modal_bottom_sheet: ^3.0.0-pre # Customizable bottom sheets
  cupertino_icons: ^1.0.8 # iOS-style icons

  # Firebase
  firebase_core: ^4.0.0 # Firebase core integration
  firebase_analytics: ^12.0.0

  #    Local
#  shared_preferences: ^2.0.15
  sqflite: ^2.3.3+1
#  image_gallery_saver: ^2.0.3
  image_gallery_saver_plus: ^4.0.1
  fluttertoast: ^8.2.12
#  share_plus:
#  easy_container: ^1.0.6

#  quran_library: ^2.0.0

  #  Quran
  quran:
    path: ./libraries/quran-1.2.2
#  quran_library:
#    path: ./libraries/quran_library-2.0.0
#  ffmpeg_kit_flutter_full: ^6.0.3
  ffmpeg_kit_flutter_new: ^3.2.0
  # Remove or comment out flutter_ffmpeg as it's being replaced by ffmpeg_kit_flutter
  # flutter_ffmpeg:
  #   path: ./flutter_ffmpeg-0.4.2


  fluttericon:
#  modal_bottom_sheet:
#  flutter_media_metadata: ^1.0.0+1
  metadata_god: ^1.0.0

  #  permission_handler:
  iconsax:
#  shimmer: ^3.0.0
  superellipse_shape: ^0.2.0
  flutter_keyboard_visibility: ^6.0.0
  group_list_view: ^1.1.1
  audio_session: ^0.1.25
  just_audio: ^0.10.4 # substitute version number
  just_audio_background: ^0.0.1-beta.15 # substitute version number
#  flutter_html:
  flutter_colorpicker: ^1.0.3
  visibility_detector: ^0.4.0+2
#  syncfusion_flutter_sliders: ^20.3.59
#  arabic_roman_conv: ^0.1.0-dev.2
#  flutter_animated_dialog: ^2.0.1  # auto_size_text: ^3.0.0
  rive: ^0.13.4 # for awesome dialog "animations"


  screenshot: ^3.0.0
#  in_app_review:

  azlistview_plus: ^3.0.0
  animate_do: ^4.2.0
#  google_maps_flutter:
  back_button_interceptor: ^8.0.4
  animations: ^2.0.11
  simple_annimated_staggered: ^0.0.3
  workmanager: ^0.7.0
#  flutter_local_notifications: ^14.1.1
  flutter_overlay_window: ^0.4.3
  flutter_displaymode: ^0.6.0


#  firebase_core:

#  provider: ^6.0.5
  path_provider: ^2.1.0
  font_awesome_flutter: ^10.4.0
  flutter_qiblah: ^3.1.0+1
#  geolocator: ^9.0.2
#  flutter_svg: ^1.1.6
  scrollable_positioned_list: ^0.3.8
#  photo_view: ^0.14.0
#  cached_network_image: ^3.2.3

  # Localization
#  easy_localization: ^3.0.5 # Multi-language support

  #  Quran
  meta: ^1.7.0
  app_settings: ^6.1.1
#  intl: ^0.17.0

  #Internet
#  dio: ^4.0.4
#  connectivity_plus: ^2.2.0

  archive: ^4.0.7
#  equatable: ^2.0.3

  responsive_builder: ^0.4.1
  scroll_to_index: ^2.1.1
  auto_size_text: ^3.0.0

  #  flutter_dotenv: ^5.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  wakelock_plus: ^1.2.8
  intl_utils: ^2.6.1
  json_annotation:

  flutter_riverpod: ^1.0.3
  state_notifier: ^0.7.2+1
  freezed_annotation:
#  cupertino_icons: ^0.1.2

  #Calender hijri
  jhijri_picker: ^1.0.1
  hijri: ^3.0.0


  #    Q
  auto_route: ^3.2.4




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.



dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
#  logger:
#  json_serializable:
#  hive_generator:
#  build_runner:
#  freezed: ^1.1.1
#  flutter_lints: ^2.0.0
#  auto_route_generator: 3.2.1
#  flutter_gen_runner:

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/features/quran/gen/ # Optional (default: lib/gen/)

  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/features\/quran\/*


flutter:

  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/quran_library/
    - assets/quran_library/fonts/
    - assets/quran_library/fonts/Kufam-Regular.ttf
    - assets/quran_library/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - assets/quran_library/fonts/UthmanicHafs_V20.ttf
    - assets/quran_library/jsons/
    - assets/quran_library/lottie/
    - assets/quran_library/svg/
    - assets/quran_library/saadiV4.db
    - assets/quran_library/en.json


    - assets/database.db

    - assets/images/background/
    - assets/images/sections/
#    - assets/images/surah/
#    - assets/images/quran/
    - assets/images/icons/asmaallah/
    - assets/images/icons/not_fount/
    - assets/images/icons/prayer/
    - assets/images/icons/favorites/
    - assets/images/icons/sebha/
    - assets/images/icons/quran/
    - assets/lang/
    - assets/images/campass/
    - assets/

    - assets/images/
    - .env
#    - assets/images/quran/
    - assets/images/app/
#    - assets/images/1024/
#    - assets/images/font/quran/
    - assets/json/
    - assets/translations/


  fonts:
    - family: kufi
      fonts:
        - asset: assets/quran_library/fonts/Kufam-Regular.ttf
    - family: naskh
      fonts:
        - asset: assets/quran_library/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - family: hafs
      fonts:
        - asset: assets/quran_library/fonts/UthmanicHafs_V20.ttf
    - family: surahName
      fonts:
        - asset: assets/quran_library/fonts/surah_name_naskh.ttf

    - family: '0'
      fonts:
        - asset: assets/fonts/rb/rb_regular.ttf
        - asset: assets/fonts/rb/rb_bold.ttf

    - family: '1'
      fonts:
        - asset: assets/fonts/janna/janna_regular.ttf
        - asset: assets/fonts/janna/janna_bold.ttf

    - family: '2'
      fonts:
        - asset: assets/fonts/al_quran/al_quran_regular.ttf
        - asset: assets/fonts/al_quran/al_quran_bold.ttf

    - family: '3'
      fonts:
        - asset: assets/fonts/uthman_taha_naskh/uthman_taha_naskh_regular.otf
        - asset: assets/fonts/uthman_taha_naskh/uthman_taha_naskh_bold.otf

    - family: '4'
      fonts:
        - asset: assets/fonts/DroidArabic.otf

    - family: '5'
      fonts:
        - asset: assets/fonts/JF.otf

    - family: '6'
      fonts:
        - asset: assets/fonts/noorehuda.ttf

    - family: '7'
      fonts:
        - asset: assets/fonts/noorehira.ttf

    - family: '8'
      fonts:
        - asset: assets/fonts/Ruqaa.ttf
    - family: quran
      fonts:
        - asset: assets/fonts/al_quran/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/fonts/al_quran/me_quran.ttf

    - family: '0'
      fonts:
        - asset: assets/fonts/rb/rb_regular.ttf
        - asset: assets/fonts/rb/rb_bold.ttf

    - family: '1'
      fonts:
        - asset: assets/fonts/janna/janna_regular.ttf
        - asset: assets/fonts/janna/janna_bold.ttf

    - family: '2'
      fonts:
        - asset: assets/fonts/al_quran/al_quran_regular.ttf
        - asset: assets/fonts/al_quran/al_quran_bold.ttf

    - family: '3'
      fonts:
        - asset: assets/fonts/uthman_taha_naskh/uthman_taha_naskh_regular.otf
        - asset: assets/fonts/uthman_taha_naskh/uthman_taha_naskh_bold.otf

    - family: '4'
      fonts:
        - asset: assets/fonts/DroidArabic.otf

    - family: '5'
      fonts:
        - asset: assets/fonts/JF.otf

    - family: '6'
      fonts:
        - asset: assets/fonts/noorehuda.ttf

    - family: '7'
      fonts:
        - asset: assets/fonts/noorehira.ttf

    - family: '8'
      fonts:
        - asset: assets/fonts/Ruqaa.ttf
    - family: quran
      fonts:
        - asset: assets/fonts/al_quran/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/fonts/al_quran/me_quran.ttf
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/amiriQuran_regular.ttf

    - family: Taha
      fonts:
        - asset: assets/fonts/taha.ttf
    - family: me
      fonts:
        - asset: assets/fonts/me_quran.ttf

    - family: UthmanicHafs13
      fonts:
        - asset: assets/fonts/uthmanicHafs1_ver13.otf

    - family: "qaloon"
      fonts:
        - asset: assets/fonts/qaloon.ttf

    - family: "pdsm"
      fonts:
        - asset: assets/fonts/pdms.otf
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: "noor ehuda"
      fonts:
        - asset: assets/fonts/noorehuda-org.ttf

    - family: "hafs-nastaleeq-ver10-org"
      fonts:
        - asset: assets/fonts/hafs-nastaleeq-ver10-org.otf
    - family: "jomhuria-regular-full-org"
      fonts:
        - asset: assets/fonts/jomhuria-regular-full-org.ttf

    - family: "mada-regular-full"
      fonts:
        - asset: assets/fonts/mada-regular-full.ttf
    - family: "markazi-text-regular-full-org"
      fonts:
        - asset: assets/fonts/markazi-text-regular-full-org.ttf
    - family: "noto-kufi-arabic-regular-full"
      fonts:
        - asset: assets/fonts/noto-kufi-arabic-regular-full.ttf

    - family: "qumbul-v7-full"
      fonts:
        - asset: assets/fonts/qumbul-v7-full.ttf
    - family: "qur-std"
      fonts:
        - asset: assets/fonts/qur-std.ttf

    - family: "shorooq-full-org"
      fonts:
        - asset: assets/fonts/shorooq-full-org.ttf

    - family: "arsura"
      fonts:
        - asset: assets/fonts/arsura.ttf

    - family: "KFGQPC Uthmanic Script HAFS Regular"
      fonts:
        - asset: assets/fonts/kfgqpc_uthmanic_script_hafs_regular.otf
    - family: "roboto"
      fonts:
        - asset: assets/fonts/roboto.ttf
