// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default `FirebaseOptions` for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_p8UI-nKaVVQwvI4RKL12C8kPXc0U0-U',
    appId: '1:691813963206:android:b0c7868bb2d7df0a5e8d4b',
    messagingSenderId: '691813963206',
    projectId: 'azkary-app',
    databaseURL: 'https://azkary-app.firebaseio.com',
    storageBucket: 'azkary-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_p8UI-nKaVVQwvI4RKL12C8kPXc0U0-U',
    appId: '1:691813963206:ios:36dcd1dbc58484675e8d4b',
    messagingSenderId: '691813963206',
    projectId: 'azkary-app',
    databaseURL: 'https://azkary-app.firebaseio.com',
    storageBucket: 'azkary-app.appspot.com',
    iosBundleId: 'com.muslim.azkar.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_p8UI-nKaVVQwvI4RKL12C8kPXc0U0-U',
    appId: '1:691813963206:ios:cbb654c5b69e2c175e8d4b',
    messagingSenderId: '691813963206',
    projectId: 'azkary-app',
    databaseURL: 'https://azkary-app.firebaseio.com',
    storageBucket: 'azkary-app.appspot.com',
    iosBundleId: 'com.muslim.azkar.app.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_p8UI-nKaVVQwvI4RKL12C8kPXc0U0-U',
    appId: '1:691813963206:windows:d18a78fc27559e8c5e8d4b',
    messagingSenderId: '691813963206',
    projectId: 'azkary-app',
    databaseURL: 'https://azkary-app.firebaseio.com',
    storageBucket: 'azkary-app.appspot.com',
    authDomain: 'azkary-app.firebaseapp.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_p8UI-nKaVVQwvI4RKL12C8kPXc0U0-U',
    appId: '1:691813963206:web:5c3f4e8c7d6b9a2f5e8d4b',
    messagingSenderId: '691813963206',
    projectId: 'azkary-app',
    databaseURL: 'https://azkary-app.firebaseio.com',
    storageBucket: 'azkary-app.appspot.com',
    authDomain: 'azkary-app.firebaseapp.com',
  );
}
